src/KWFCI/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using KWFCI.Models;
using Microsoft.AspNetCore.Identity;
using KWFCI.Repositories;
using KWFCI.Models.ViewModels;
using Microsoft.EntityFrameworkCore;

namespace KWFCI.Controllers
{
    
    [Route("Index")]
    [Route("/")]
    [Authorize(Roles = "Staff")]
    public class HomeController : Controller
    {
        private UserManager<StaffUser> userManager;
        private IStaffProfileRepository staffProfRepo;
        private IKWTaskRepository taskRepo;
        private IInteractionsRepository intRepo;
        private IBrokerRepository brokerRepo;
        

        public HomeController(UserManager<StaffUser> usrMgr, IStaffProfileRepository repo, IKWTaskRepository repo2, IInteractionsRepository repo3, IBrokerRepository repo4)
        {
            staffProfRepo = repo;
            userManager = usrMgr;
            taskRepo = repo2;
            intRepo = repo3;
            brokerRepo = repo4;
        }
        
        public async Task <IActionResult> Index()
        {
            /*Login Logic*/
            StaffUser user = await userManager.FindByNameAsync(User.Identity.Name);
            Helper.StaffUserLoggedIn = user;
            Helper.StaffProfileLoggedIn = Helper.DetermineProfile(staffProfRepo);
            /*End Login Logic*/

            /*Call the GetToday method of the helper class to get and set today's date for use with datepicker validation*/
            Helper.GetToday();

            /* Priority reassignment Logic */
            var tasks = taskRepo.GetAllKWTasks().Where(t => t.Type != "Onboarding");

            
            foreach (KWTask t in tasks.ToList())
            {
                int diff = (int)(t.DateDue - DateTime.Today).Value.TotalDays;
                if (diff < 0 && t.Priority < 5)
                {
                    StaffProfile profile = staffProfRepo.GetProfileByTask(t);

                    t.Priority = 5;
                    taskRepo.UpdateKWTask(t);

                    if (profile != null)
                    {
                        profile.Tasks.Remove(t);
                        staffProfRepo.UpdateStaff(profile);
                    }
                }
                else if (diff == 0 && t.Priority < 4)
                {
                    t.Priority = 4;
                    taskRepo.UpdateKWTask(t);
                }

                else if (diff <= 2 && t.Priority < 3)
                {
                    t.Priority = 3;
                    taskRepo.UpdateKWTask(t);
                }

                else if (diff == 3 && t.Priority < 2)
                {
                    t.Priority = 2;
                    taskRepo.UpdateKWTask(t);
                }
            }

            

            /*Display Alerts Logic*/
            ViewBag.Name = Helper.StaffProfileLoggedIn.FirstName;
            ViewBag.Alerts = Helper.StaffProfileLoggedIn.Tasks.Where(
                t => t.Type == "Alert" && 
                (DateTime.Compare(DateTime.Now, t.AlertDate.GetValueOrDefault()) == 0 ||
                DateTime.Compare(DateTime.Now, t.AlertDate.GetValueOrDefault()) > 0)).ToList();

            var criticalVB = taskRepo.GetAllTasksByType("Alert").Where(t => t.Priority == 5).ToList();

            foreach(KWTask task in taskRepo.GetAllTasksByType("Task").Where(t => t.Priority == 5).ToList())
            {
                criticalVB.Add(task);
            }

            ViewBag.Critical = criticalVB;
             
            /*End Display Alerts Logic*/

            /*Populate ViewModel Logic*/
            var vm = new HomeVM();
            
            /*TODO Be aware this directly queries the database, may break if StaffProfile or KWTask models change*/
            string sqlGlobal = "SELECT * FROM dbo.KWTasks WHERE StaffProfileID IS NULL";
            string sqlPersonal = "SELECT * FROM dbo.KWTasks WHERE StaffProfileID = " + Helper.StaffProfileLoggedIn.StaffProfileID;
            vm.GlobalTasks = taskRepo.GetTasksFromSQL(sqlGlobal).Where(t => t.Type != "Onboarding").ToList();
            vm.PersonalTasks = taskRepo.GetTasksFromSQL(sqlPersonal).Where(t => t.Type != "Onboarding").ToList();

            List<Broker> brokers = new List<Broker>();
            foreach(Interaction i in Helper.StaffProfileLoggedIn.Interactions)
            {
                foreach (Broker b in brokerRepo.GetAllBrokers())
                {
                    if(b.Interactions.Contains(i))
                    {
                        i.BrokerName = b.FirstName + " " + b.LastName;

                        if (!brokers.Contains(b))
                            brokers.Add(b);
                    }
                }
            }
            ViewBag.Brokers = brokers;


            vm.PersonalInteractions = Helper.StaffProfileLoggedIn.Interactions;
            vm.NewTask = new KWTask();
            vm.NewBroker = new Broker();
            vm.NewMessage = new Message();
            vm.StaffList = staffProfRepo.GetAllStaffProfiles().ToList();
            /*End Populate ViewModel Logic*/

            return View(vm);
        }
    }
}

src/KWFCI/Controllers/KWTasksController.cs
using KWFCI.Models;
using KWFCI.Models.ViewModels;
using KWFCI.Repositories;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace KWFCI.Controllers
{
    [Authorize(Roles = "Staff")]
    [Route("Tasks")]
    public class KWTasksController : Controller
    {
        private IKWTaskRepository taskRepo;
        private IStaffProfileRepository staffRepo;
        private IInteractionsRepository intRepo;

        public KWTasksController(IKWTaskRepository repo, IStaffProfileRepository repo2, IInteractionsRepository repo3)
        {
            taskRepo = repo;
            staffRepo = repo2;
            intRepo = repo3;
        }
        //[Route("Index")]
        public IActionResult AllKWTasks(string filter)
        {
            /*Call the GetToday method of the helper class to get and set today's date for use with datepicker validation*/
            Helper.GetToday();

            var criticalVB = taskRepo.GetAllTasksByType("Alert").Where(t => t.Priority == 5).ToList();

            foreach (KWTask task in taskRepo.GetAllTasksByType("Task").Where(t => t.Priority == 5).ToList())
            {
                criticalVB.Add(task);
            }

            ViewBag.Critical = criticalVB;

            ViewBag.Filter = filter;
            var vm = new KWTaskVM();
            vm.StaffList = staffRepo.GetAllStaffProfiles().ToList();
            var KWTasks = taskRepo.GetAllKWTasks().Where(t => t.Type != "Onboarding").ToList();

            foreach(KWTask t in KWTasks.ToList())
            {
                if(t.Priority == 5)
                {
                    StaffProfile profile = staffRepo.GetProfileByTask(t);
                    if(profile != null)
                    {
                        profile.Tasks.Remove(t);
                        staffRepo.UpdateStaff(profile);
                    }
                }
                foreach(StaffProfile s in vm.StaffList)
                {
                    if(s.Tasks.Contains(t))
                    {
                        t.StaffName = s.FirstName + " " + s.LastName;
                        t.StaffEmail = s.Email;
                    }
                }
            }
            vm.KWTasks = KWTasks;
            vm.NewKWTask = new KWTask();
            return View(vm);
        }

        [Route("Add")]
        [HttpPost]
        public IActionResult AddKWTask(KWTaskVM vm, int? staffProfileID, string returnURL)
        {
            var kwtask = new KWTask
            {
                Message = vm.NewKWTask.Message,
                AlertDate = vm.NewKWTask.AlertDate,
                DateCreated = vm.NewKWTask.DateCreated,
                DateDue = vm.NewKWTask.DateDue,
                Priority = vm.NewKWTask.Priority
            };
            if (kwtask.AlertDate == null)
                kwtask.Type = "Task";
            else
                kwtask.Type = "Alert";

            if(staffProfileID != null)
            {
                StaffProfile staff = staffRepo.GetStaffProfileByID((int)staffProfileID);
                staff.Tasks.Add(kwtask);
            }

            taskRepo.AddKWTask(kwtask);

            //TODO: See if there is a way to just close the modal and not refresh the page
            return Redirect(returnURL);
        }

        [HttpPost]
        public IActionResult Delete(int id)
        {
            KWTask kwtask = taskRepo.GetKWTaskByID(id);
            if (kwtask != null)
            {
                var interaction = taskRepo.GetAssociatedInteraction(kwtask);
                if (interaction != null)
                {
                    interaction.Task = null;
                    interaction.TaskForeignKey = null;
                    intRepo.UpdateInteraction(interaction);
                }
                    
                taskRepo.DeleteKWTask(kwtask);
                return RedirectToAction("AllKWTasks");
            }
            else
            {
                ModelState.AddModelError("", "Task Not Found");
            }
            return RedirectToAction("AllKWTasks");
        }

        [Route("Edit")]
        [HttpPost]
        public ActionResult Edit(KWTaskVM vm, int KWTaskID)
        {
            KWTask kwtask = taskRepo.GetKWTaskByID(KWTaskID);
            kwtask.Message = vm.NewKWTask.Message;
            kwtask.AlertDate = vm.NewKWTask.AlertDate;
            kwtask.DateDue = vm.NewKWTask.DateDue;
            kwtask.Priority = vm.NewKWTask.Priority;
            kwtask.Type = vm.NewKWTask.Type;

            if (kwtask.AlertDate == null)
                kwtask.Type = "Task";
            else
                kwtask.Type = "Alert";

            int verify = taskRepo.UpdateKWTask(kwtask);
            if (verify == 1)
            {
                return RedirectToAction("AllKWTasks");
            }
            else
            {
                ModelState.AddModelError("", "Task Not Found");
            }
            return RedirectToAction("AllKWTasks");
        }

        [Route("Assign")]
        [HttpPost]
        public ActionResult Assign(int KWTaskID, string StaffProfileName)
        {
            bool verify;
            var task = taskRepo.GetKWTaskByID(KWTaskID);
            var allProfiles = staffRepo.GetAllStaffProfiles().ToList();
            if (StaffProfileName != "Clear")
            {
                string[] name = StaffProfileName.Split(' ');
                var profile = staffRepo.GetStaffProfileByFullName(name[0], name[1]) as StaffProfile;
                verify = ProcessAssign(task, allProfiles, profile);

                if (verify)
                {
                    return RedirectToAction("AllKWTasks");
                }
                else
                {
                    ModelState.AddModelError("", "Task Not Found");
                }
            }
            else
            {
                verify = ProcessAssign(task, allProfiles, true);
            }
            
            return RedirectToAction("AllKWTasks");
        }


        //First unassigns the task from staff, then assigns it, then updates the repo
        private bool ProcessAssign(KWTask t, List<StaffProfile> sps, StaffProfile staff)
        {
            foreach(StaffProfile sp in sps)
            {
                if (sp.Tasks.Contains(t))
                    sp.Tasks.Remove(t);
            }
            staff.Tasks.Add(t);
            int verify = staffRepo.UpdateStaff(staff);
            if (verify > 0)
                return true;
            else
                return false;
        }

        private bool ProcessAssign(KWTask t, List<StaffProfile> sps, bool clear)
        {
            foreach (StaffProfile sp in sps)
            {
                if (sp.Tasks.Contains(t))
                {
                    sp.Tasks.Remove(t);
                    staffRepo.UpdateStaff(sp);
                }
            }
            return true;
        }
    }
}

src/KWFCI/Views/Home/Index.cshtml
@model HomeVM
@using KWFCI.Models.ViewModels
<div class="row">
    <div class="col-xs-12" style="text-align:center;">

        <h1>Welcome @ViewBag.Name</h1>
    </div>
</div>

@if (ViewBag.Alerts != null)
{
    if (ViewBag.Alerts.Count > 0)
    {
        <div class="row">
            <div class="col-xs-12" style="text-align:center;">
                @if (ViewBag.Alerts.Count > 1)
                {
                <h3><a href="@Url.Action("AllKWTasks", "KWTasks", new { filter = "Alert " + ViewBag.Name })">You have @ViewBag.Alerts.Count Alerts</a></h3>
                }
                else
                {
                    <h3><a href="@Url.Action("AllKWTasks", "KWTasks", new { filter = "Alert " + ViewBag.Name })">You have @ViewBag.Alerts.Count Alert</a></h3>

                }
             </div>
        </div>
    }
}
<div class="row" style="margin-top:30px;">
    <div class="col-xs-12">
        <div class="row">

            <div class="col-xs-5 col-xs-offset-1" style="padding-left:15px;">
                <div style="float:none;display:flex;justify-content:space-between;">
                    <a href="/Brokers" class="btn btn-success btn-md" style="height:100%;width:45%;">
                        <span class="glyphicon glyphicon-user" aria-hidden="true"></span>
                        View Brokers
                    </a>
                    <a href="#" class="btn btn-success btn-md grab-url" data-toggle="modal" data-target="#newBroker" style="height:100%;width:45%; margin-right:23px;">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
                        Add Broker
                    </a>
                </div>
            </div>
            <div class="col-xs-5" style="padding-left:15px;">
                <div style="float:none;display:flex;justify-content:space-between;">
                    <a class="btn btn-md btn-success grab-url" href="#" style="height:100%;width:45%;" data-target="#addKWTaskModal" data-toggle="modal">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
                        Create Task
                    </a>
                    <a href="#" class="btn btn-success grab-url  btn-md" data-toggle="modal" data-target="#newMessage" style="height:100%;width:45%;margin-right:23px;">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
                        Create Message
                    </a>

                </div>
            </div>
        </div>
    </div>
</div>

<div class="row" id="homepage-tasks">
    <div class="col-xs-5 col-xs-offset-1" style="text-align:center;">
        <div class="panel panel-default" style="width:96%; height:375px; margin-top:50px;">
            <div class="panel-heading text-center"><h2><a href="/Tasks?filter=@ViewBag.Name task">My Tasks</a></h2></div>
            <div class="panel-body">
                @Html.Partial("_HomePageTasks", Model.PersonalTasks)
            </div>
        </div>
    </div>

    <div class="col-xs-5" style="text-align:center;">
        <div class="panel panel-default" style="width:96%; height:375px; margin-top:50px;">
            <div class="pull-right panel-heading text-center" style="width:100%;"><h2><a href="/Tasks">All Tasks</a></h2></div>
            <div class="panel-body">
                @Html.Partial("_HomePageTasks", Model.GlobalTasks)
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-xs-10 col-xs-offset-1" style="text-align:center;">
        <div class="panel panel-default" style="width:100%; margin-top:30px;">
            <div class="panel-heading text-center" style="width:100%;"><h2>My Interactions</h2></div>
            <div class="panel-body">
                @Html.Partial("_StaffInteractions", new HomeStaffInteractionsVM() {Brokers = ViewBag.Brokers, PersonalInteractions = Model.PersonalInteractions })
                
            </div>
        </div>
    </div>
</div>

@Html.Partial("Modals/_AddBrokerModal", Model.NewBroker)    

@Html.Partial("Modals/_AddKWTaskModal", new KWTaskVM() { NewKWTask = Model.NewTask, StaffList=Model.StaffList })
@Html.Partial("Modals/_AddMessageModal", Model.NewMessage)

src/KWFCI/Views/Home/_HomePageTasks.cshtml
@model List<KWTask>

<div class="row">
    <div class="col-xs-12">
        <table class="table">
            <thead>
                <tr>
                    <th>Message</th>
                    <th>Date Due</th>
                    <th>Priority</th>
                </tr>
            </thead>
            <tbody>
                @foreach (KWTask t in Model)
                {
                    <tr>
                        <td>@t.Message</td>
                        <td>
                            @{
                                //Remove the time from the display
                                string[] splitDateDue = t.DateDue.ToString().Split(' ');
                                string dateDue = splitDateDue[0];

                                @dateDue
                            }
                        </td>
                        <td>
                            @if (t.Priority == 5)
                            {
                                @:Critical
                            }
                            else
                            {
                                @t.Priority
                            }
                        </td>
                    </tr>
                                }
            </tbody>
        </table>
    </div>
</div>

src/KWFCI/Views/Home/_StaffInteractions.cshtml
@model KWFCI.Models.ViewModels.HomeStaffInteractionsVM
@using KWFCI.Models.ViewModels

<div class="row">
    <div class="col-xs-12">
        <table class="table table-bordered table-hover editTable">
            <thead class="row">
                <tr>
                    <th class="col-xs-2">Broker</th>
                    <th class="col-xs-4">Notes</th>
                    <th class="col-xs-2">Date</th>
                    <th class="col-xs-4">Next Step</th>
                </tr>
            </thead>
            <tbody class="row">
                @foreach (Interaction a in Model.PersonalInteractions)
                {
                    foreach (Broker b in Model.Brokers)
                    {
                        if (b.Interactions.Contains(a))
                        {
                            <tr style="height:100%;">
                                <td class="col-xs-2">
                                    <div class="alignCell-Parent">

                                        <div class="alignCell">
                                            <a href="@Url.Action("BrokerInteractions", "Interactions", new { BrokerID = b.BrokerID })">
                                                @b.FirstName @b.LastName
                                            </a> 
                                        </div>
                                    </div>
                                </td>
                                <td class="col-xs-4">
                                    <div class="col-xs-12">
                                        <div class="alignCell-Parent"><span class="alignCell ellipsis">@a.Notes</span></div>
                                    </div>
                                </td>
                                <td class="col-xs-2">
                                    @a.DateCreated
                                </td>
                                <td class="col-xs-4" style="height:100%;">
                                    <div class="col-xs-10" style="height:100%;">
                                        <div style="height:100%;" class="ellipsis"><span class="align-middle">@a.NextStep</span></div>
                                    </div>
                                </td>
                            </tr>
                        }
                    }
                }
            </tbody>
        </table>
    </div>
</div>